# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BmmnerpPplfU53Ej7vEiYVfXLB_WTgI
"""

class Burung:

    def __init__(self):
        pass

class BurungTerbang(Burung):


    def terbang(self):
        print("Mengepakan sayap")
        return true
class Elang(BurungTerbang):
    def __init__(self):
        pass

class Penguin(Burung):
    def __init__(self):
        pass