# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BmmnerpPplfU53Ej7vEiYVfXLB_WTgI
"""

import math
class Lingkaran(BangunDatar):

    def __init__(self, radius):
        self.radius = radius
    def luas(self):
        return math.pi * pow(self.radius, 2)
class Persegi(BangunDatar):

    def __init__(self, panjang):
        self.panjang = panjang
    def luas(self):
        return pow(self.panjang, 2)
class Kalkulasi:

    def __init__(self, *args):
        self.bangunDatar = args

 def calculate(self):
        listLuas = []
        for objek in self.bangunDatar:
            luas = objek.luas()
            listLuas.append(luas)

        return sum(listLuas)


    def output(self):
        return self.calculate()

if __name__ == "__main__":

    result = Kalkulasi(
        Lingkaran(2),
        Persegi(5),
        Persegi(6)
    )

    print("Jumlah luas dari bangunan ", result.output())

class BangunDatar:

    def luas():
        pass